// state/initialState.ts

export const initialState = {
  markets: {
    name: "Global Markets",
    stabilityIndex: 0.55,
    riskIndex: 0.45,
    liquidityIndex: 0.6,
    volatilityIndex: 0.4,
    dignityIndex: 0.5,
    extractionIndex: 0.55,
    collapseRiskIndex: 0.4,
    ecologicalDependencyIndex: 0.5,
    infrastructureDependencyIndex: 0.6,
    workforceDependencyIndex: 0.55,
    governanceDependencyIndex: 0.5,
    populationDependencyIndex: 0.5,
  },

  ecology: {
    name: "Global Ecology",
    stabilityIndex: 0.5,
    riskIndex: 0.5,
    regenerationIndex: 0.45,
    pollutionIndex: 0.55,
    depletionIndex: 0.5,
    dignityIndex: 0.5,
    collapseRiskIndex: 0.45,
    infrastructureDependencyIndex: 0.55,
    populationDependencyIndex: 0.5,
    governanceDependencyIndex: 0.5,
    marketDependencyIndex: 0.5,
  },

  infrastructure: {
    name: "Global Infrastructure",
    stabilityIndex: 0.6,
    riskIndex: 0.4,
    resilienceIndex: 0.55,
    dignityIndex: 0.5,
    stressIndex: 0.45,
    collapseRiskIndex: 0.35,
    ecologicalDependencyIndex: 0.5,
    workforceDependencyIndex: 0.6,
    governanceDependencyIndex: 0.55,
    marketDependencyIndex: 0.5,
    populationDependencyIndex: 0.5,
  },

  workforce: {
    name: "Global Workforce",
    stabilityIndex: 0.55,
    riskIndex: 0.45,
    resilienceIndex: 0.5,
    dignityIndex: 0.55,
    cohesionIndex: 0.5,
    conflictIndex: 0.45,
    stressIndex: 0.5,
    burnoutIndex: 0.45,
    collapseRiskIndex: 0.4,
    ecologicalDependencyIndex: 0.5,
    infrastructureDependencyIndex: 0.55,
    governanceDependencyIndex: 0.5,
    marketDependencyIndex: 0.55,
    populationDependencyIndex: 0.5,
  },

  governance: {
    name: "Global Governance",
    stabilityIndex: 0.5,
    riskIndex: 0.5,
    coordinationIndex: 0.45,
    dignityIndex: 0.5,
    consensusIndex: 0.45,
    conflictIndex: 0.5,
    responsivenessIndex: 0.5,
    ecologicalDependencyIndex: 0.5,
    infrastructureDependencyIndex: 0.55,
    workforceDependencyIndex: 0.5,
    marketDependencyIndex: 0.5,
    collapseRiskIndex: 0.45,
  },

  population: {
    name: "Global Population",
    stabilityIndex: 0.55,
    riskIndex: 0.45,
    resilienceIndex: 0.5,
    dignityIndex: 0.55,
    cohesionIndex: 0.5,
    conflictIndex: 0.45,
    stressIndex: 0.5,
    burnoutIndex: 0.45,
    ecologicalDependencyIndex: 0.5,
    infrastructureDependencyIndex: 0.55,
    workforceDependencyIndex: 0.5,
    marketDependencyIndex: 0.5,
    governanceDependencyIndex: 0.5,
    collapseRiskIndex: 0.4,
  },

  rights: {
    name: "Global Rights",
    dignityIndex: 0.55,
    autonomyIndex: 0.5,
    safetyIndex: 0.55,
    accessIndex: 0.5,
    fairnessIndex: 0.5,
    predatoryPressureIndex: 0.45,
    exclusionIndex: 0.45,
    exploitationIndex: 0.45,
    governanceDependencyIndex: 0.5,
    marketDependencyIndex: 0.5,
    workforceDependencyIndex: 0.5,
    infrastructureDependencyIndex: 0.5,
    ecologicalDependencyIndex: 0.5,
    collapseRiskIndex: 0.4,
  },

  par: {
    name: "PAR Currency",
    stabilityIndex: 0.5,
    riskIndex: 0.5,
    dignityIndex: 0.55,
    adoptionIndex: 0.0, // starts at zero — voluntary adoption only
    renewableBackingIndex: 0.5,
    collapseRiskIndex: 0.4,
    marketDependencyIndex: 0.5,
    governanceDependencyIndex: 0.5,
    populationDependencyIndex: 0.5,
    ecologyDependencyIndex: 0.5,
    infrastructureDependencyIndex: 0.5,
  },

  commons: {
    name: "Global Commons",
    stabilityIndex: 0.5,
    riskIndex: 0.5,
    regenerationIndex: 0.45,
    stewardshipIndex: 0.5,
    dignityIndex: 0.5,
    extractionPressureIndex: 0.5,
    depletionIndex: 0.5,
    pollutionIndex: 0.5,
    ecologicalDependencyIndex: 0.5,
    infrastructureDependencyIndex: 0.5,
    populationDependencyIndex: 0.5,
    governanceDependencyIndex: 0.5,
    marketDependencyIndex: 0.5,
    collapseRiskIndex: 0.45,
  },
}